package org.slave.minecraft.retweak.resources;

import com.google.common.base.Joiner;
import cpw.mods.fml.common.ModContainer;
import org.slave.minecraft.library.api.Metadata;
import org.slave.minecraft.library.helpers.ModHelper;
import org.slave.minecraft.retweak.ReTweakMod;

/**
 * Created by Master801 on 3/19/2016 at 7:56 AM.
 *
 * @author Master801
 */
public final class ReTweakMetadata implements Metadata {

    public static final Metadata INSTANCE = new ReTweakMetadata();

    private ReTweakMetadata() {
    }

    @Override
    public String[] getAuthorList() {
        return new String[] {
                "Master801"
        };
    }

    @Override
    public boolean isAutoGenerated() {
        return false;
    }

    @Override
    public ModContainer[] getChildMods() {
        return null;
    }

    @Override
    public String getCredits() {
        return Joiner.on(System.lineSeparator()).join(new String[] {
                "FyberOptic - Intermediary"
        });
    }

    @Override
    public String getDescription() {
        return Joiner.on(System.lineSeparator()).join(new String[] {
                ""
        });
    }

    @Override
    public String getLogo() {
        return null;
    }

    @Override
    public String getModID() {
        return ModHelper.getReflectiveModID(ReTweakMod.class);
    }

    @Override
    public String getModName() {
        return ModHelper.getReflectiveModName(ReTweakMod.class);
    }

    @Override
    public String getParentMod() {
        return null;
    }

    @Override
    public String[] getScreenShots() {
        return null;
    }

    @Override
    public String getUpdateURL() {
        return null;
    }

    @Override
    public String getURL() {
        return null;
    }

    @Override
    public String getModVersion() {
        return ModHelper.getReflectiveModVersion(ReTweakMod.class);
    }
}
