package org.slave.minecraft.retweak.util;

import com.google.common.base.Joiner;
import cpw.mods.fml.common.ModContainer;
import net.minecraft.util.EnumChatFormatting;
import org.slave.minecraft.library.api.Metadata;
import org.slave.minecraft.library.helpers.ChatHelper;
import org.slave.minecraft.library.helpers.ModHelper;
import org.slave.minecraft.retweak.ReTweakMod;

/**
 * Created by Master801 on 3/19/2016 at 7:56 AM.
 *
 * @author Master801
 */
public final class ReTweakMetadata implements Metadata {

    public static final Metadata INSTANCE = new ReTweakMetadata();

    private ReTweakMetadata() {
    }

    @Override
    public String[] getAuthorList() {
        return new String[] {
                ChatHelper.formatString(
                        "Master801",
                        EnumChatFormatting.AQUA
                )
        };
    }

    @Override
    public boolean isAutoGenerated() {
        return false;
    }

    @Override
    public ModContainer[] getChildMods() {
        return null;
    }

    @Override
    public String getCredits() {
        return Joiner.on(
                '\n'
        ).join(
                new String[]{
                        ChatHelper.formatString(
                                "FyberOptic - Intermediary",
                                EnumChatFormatting.DARK_GREEN
                        )
                }
        );
    }

    @Override
    public String getDescription() {
        return Joiner.on(
                "\n\n"
        ).join(
                new String[]{
                        "Loads [some] Forge mods from [some] previous versions of Minecraft.",
                        ChatHelper.formatString(
                                "Uses trickery and may cause crashes. Use at your own risk.",
                                EnumChatFormatting.DARK_RED
                        )
                }
        );
    }

    @Override
    public String getLogo() {
        return null;
    }

    @Override
    public String getModID() {
        return ChatHelper.formatString(
                ModHelper.getReflectiveModID(ReTweakMod.class),
                EnumChatFormatting.DARK_AQUA
        );
    }

    @Override
    public String getModName() {
        return ChatHelper.formatString(
                ModHelper.getReflectiveModName(ReTweakMod.class),
                EnumChatFormatting.DARK_RED
        );
    }

    @Override
    public String getParentMod() {
        return null;
    }

    @Override
    public String[] getScreenShots() {
        return null;
    }

    @Override
    public String getUpdateURL() {
        return null;
    }

    @Override
    public String getURL() {
        return null;
    }

    @Override
    public String getModVersion() {
        return ChatHelper.formatString(
                ModHelper.getReflectiveModVersion(ReTweakMod.class),
                EnumChatFormatting.LIGHT_PURPLE
        );
    }

}
